runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: index.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest