runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: index.py

- url: /bootstrap
  static_dir: bootstrap

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest