runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /.*
  script: index.app

libraries:
- name: webapp2
  version: latest

env_variables:
  FIREBASE_PROJECT_ID: 'wellbeing-app-cloud-computing'