runtime: python27
api_version: 1
threadsafe: true
service: backend

handlers:
- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: index.app

libraries:
- name: webapp2
  version: latest
- name: MySQLdb
  version: "latest"

env_variables:
  CLOUDSQL_CONNECTION_NAME:  wellbeing-app-cloud-computing:australia-southeast1:wellbeing-sql
  CLOUDSQL_USER: root
  FIREBASE_PROJECT_ID: 'wellbeing-app-cloud-computing'
  GAE_USE_SOCKETS_HTTPLIB : 'true'